### ISSUE TITLE
Store has already been added app

### ISSUE THREAD

**Issue by yarrgh** [ngxs/core#69]
Currently I have 2 stores, AppStore and AuthStore. AppStore is controlled by the AppModule for general all-purpose states for the app. AuthStore is managed by the AuthModule.

In AppModule:
```typescript
  imports: [
    //...
    NgxsModule.forRoot([AppStore]),
    AuthModule,
    // ...
  ]
```

In AuthModule:
```typescript
  imports: [
    //...
    NgxsModule.forFeature([AuthStore]),
    AuthModule,
    // ...
  ]
```

If I do this in AuthModule, I get an error:

> Error: Store has already been added app
>     at _loop_1 (ngxs-api.js:77)
>     at StoreFactory.add (ngxs-api.js:98)
>     at StoreFactory.addAndReturnDefaults (ngxs-api.js:114)
>     at NgxsFeatureModule.initStores (ngxs-api.js:455)
>     at new NgxsFeatureModule (ngxs-api.js:451)
>     at _createClass (core.js:10895)
>     at _createProviderInstance$1 (core.js:10865)
>     at initNgModule (core.js:10818)
>     at new NgModuleRef_ (core.js:12073)
>     at createNgModuleRef (core.js:12062)

AuthModule isn't LazyLoaded. If I removed the import from AuthModule and add the AuthStore to the import in AppModule it works. I'd rather not add the AuthStore into the AppModule if I can help it.

Am I not doing this correctly? Does `forFeature()` only work if the module is lazy loaded?

**Comment by yarrgh** [comment]
If I change AuthModule to use `forRoot()` instead of `forFeature()` it works. Not at all what I was expecting. Usually `forRoot()` means it should only be called once from a root module.

**Comment by amcdnl** [comment]
`forFeature` is only for lazy loaded routes. You should import it in the `forRoot` in this case.

**Comment by un33k** [comment]
@amcdnl I am not sure about this. Ngrx had the same problem, lots of people nagged, they finally allowed empty forRoot([]) when they move to ngrx/platform.

Not all features are meant to be lazyLoaded. A self-contained module should be able to take care of its own store and everything that goes with it.

For example, think of an Auth module. Just because it is put it it's own module in a libs/ directory, doesn't mean that it has to be lazyLoaded. Here app.module.ts imports auth authModule doesn't have to worry about anything else.

I wonder if there are any restrictions that prevent forRoot([]) implementation?

**Comment by amcdnl** [comment]
@un33k - I'm down for trying that. @deebloo - this sounds like up your alley.

**Comment by deebloo** [comment]
@yarrgh I think this may have been fixed by @leon work with the feature modules. can you check again with the latest rc?

**Comment by yarrgh** [comment]
With 2.0.0-rc.18 I get a different error. 
>'NgxsModule.forRoot()' was not called at the root module

I do have `NgxsModule.forRoot([]),` in my app.module.ts and immediately after I'm importing my AuthModule that imports `NgxsModule.forFeature([AuthState])`. If I remove the `forFeature()` import form my AuthModule it works (except for the AuthState not being set up, obviously).

**Comment by yarrgh** [comment]
Here's a StackBlitz demonstrating the error:

https://stackblitz.com/edit/ngxs-simple-amvqoh

**Comment by mailok** [comment]
@yarrgh the problen is with the feature. if you remove **AuthModule** from :
```
@NgModule({
  imports:      [ 
    BrowserModule, 
    NgxsModule.forRoot([CountState]),
    AuthModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
```
works correctly.

The problem is:

```
@NgModule({
  imports: [
    CommonModule,
    NgxsModule.forFeature([AuthState]),
  ],
  declarations: [],
  exports: [],
  providers: []
})
```
You use **AuthState** with forFeature function, but **AuthModule**  I not being loaded lazy loading

**Comment by yarrgh** [comment]
From @un33k's comment:

>Not all features are meant to be lazyLoaded. A self-contained module should be able to take care of its own store and everything that goes with it.

I think `forFeature()` should work for non lazy loaded modules as well as lazy loaded modules. Having AuthModule be lazy loaded doesn't make much sense since it is always needed in every aspect of my app.

Maybe if it is easier have a `forFeature()` for non lazy loaded modules and a `forLazyFeature()` for lazy loaded modules?

**Comment by mailok** [comment]
@yarrgh I agree with you! ```forFeature() ``` should work for non lazy loaded modules as well as lazy loaded modules.
it seems that's the bug

**Comment by yarrgh** [comment]
Closing this issue now that the fix has been released
