### ISSUE TITLE
Firefox 57, 59 - Demo not working (ReferenceError: event is not defined)

### ISSUE THREAD

**Issue by pmd500** [ngxs/core#99]
Tried the demo in Firefox https://stackblitz.com/edit/ngxs-simple?file=app%2Fapp.module.ts

However this error occurred:
```
ReferenceError: event is not defined
Stack trace:
Store.prototype._dispatch/<@https://ngxs-simple.stackblitz.io/turbo_modules/ngxs@2.0.0-rc.7/bundles/ngxs-api.umd.js:443:17
```

Also recreated the demo in a standalone environment and encountered the same error. Worked fine on chrome. This was on ubuntu linux.

**Comment by PierreDuc** [comment]
Problem seems to be [here](https://github.com/amcdnl/ngxs/blob/f00799469b94a1d2a007695a611428a76a02eef2/src/store.ts#L76):

**Comment by amcdnl** [comment]
Fixed in rc16
